spring.application.name=puntosBonus
server.port=8080

# ===============================
# CONFIGURACIÓN DE POSTGRESQL (DOCKER)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5434/flyaway_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true